Repository AliceO2Group/RunConditionTable, pull requests merged in 2023-08, with the labels that each got.

#150 ORCT-135 - add view runsPerPeriod
  app/lib/server/controllers/run.controller.js
  app/lib/server/routers/period.router.js
  app/lib/services/runs/RunService.js
Labels: enhancement, backend

#149 ORCT-124 Make sidebar collapsible
  app/public/components/detectors/detectorIcon.js
  app/public/components/sidebar/sidebar.js
  app/public/components/sidebar/sidebarItem.js
  app/public/components/table/pager.js
  app/public/components/table/title.js
  app/public/styles/components/sidebar.less
  app/public/styles/ehevi/custom/components/sidebar.css
  app/public/styles/ehevi/custom/input/select.css
  app/public/styles/images/icons/15/off-white/anchorage-per-dp.svg
  app/public/styles/images/icons/15/off-white/anchored-per-mc.svg
  app/public/styles/images/icons/15/off-white/data-passes.svg
  app/public/styles/images/icons/15/off-white/detector.svg
  app/public/styles/images/icons/15/off-white/mc.svg
  app/public/styles/images/icons/15/off-white/periods.svg
  app/public/styles/images/icons/15/off-white/qa.svg
  app/public/styles/images/icons/15/off-white/runs-per-dp.svg
  app/public/styles/images/icons/15/off-white/runs-per-period.svg
  app/public/styles/images/icons/15/off-white/settings.svg
  app/public/styles/images/icons/20/off-white/detector.svg
  app/public/styles/images/icons/index.less
  app/public/views/userView/data/pageSettings/pageSettings.js
  app/public/views/userView/data/table/filtering/filter.js
Labels: frontend

#157 Docs/getting started md update
  docs/GETTING-STARTED.md
  package.json
Labels: documentation

#161 [ORCT-140] endpoint for updating quality
  app/lib/database/DatabaseManager.js
  app/lib/database/repositories/Repository.js
  app/lib/database/repositories/index.js
  app/lib/server/controllers/run.controller.js
  app/lib/server/routers/run.router.js
  app/lib/services/runs/RunService.js
  app/lib/utils/errors.js
  app/lib/utils/index.js
  package-lock.json
  package.json
  test/database/Repository.test.js
  test/database/index.js
  test/lib/server/routes.test.js
Labels: enhancement, backend

#162 [ORCT-46] Multiselect improvement
  app/public/components/buttons/dataActionButtons.js
  app/public/model/DataAccessModel.js
  app/public/model/data/FetchedDataManager.js
  app/public/styles/images/icons/20/off-white/hide.svg
  app/public/styles/images/icons/20/primary/hide.svg
  app/public/styles/images/icons/index.less
  app/public/views/flags/overview/flagsContent.js
  app/public/views/runs/runsPerDataPass/overview/content.js
  app/public/views/runs/runsPerPeriod/overview/content.js
  app/public/views/userView/data/flagsDataPanel.js
  app/public/views/userView/data/table/tablePanel.js
Labels: frontend, refactor

#167 [ORCT-145] - add pagination support
  app/lib/domain/dtos/stdRequest.dto.js
  app/lib/services/dataPasses/DataPassService.js
  app/lib/services/periods/PeriodService.js
  app/lib/services/qualityControl/QualityControlService.js
  app/lib/services/runs/RunService.js
Labels: enhancement, backend

#169 [ORCT-150] - periods endpoint not working after providing pagination
  app/lib/services/periods/PeriodService.js
  test/lib/server/routes.test.js
Labels: bug, backend

#170 [ORCT-152] - ordering support on backend
  app/lib/database/repositories/Repository.js
  app/lib/database/repositories/RunRepository.js
  app/lib/database/utilities/QueryBuilder.js
  app/lib/database/utilities/index.js
  app/lib/domain/dtos/stdRequest.dto.js
  app/lib/services/dataPasses/DataPassService.js
  app/lib/services/periods/PeriodService.js
  app/lib/services/qualityControl/QualityControlService.js
  app/lib/services/runs/RunService.js
  app/lib/services/simulationPasses/SimulationPassService.js
  app/lib/utils/deepmerge.js
  app/lib/utils/index.js
Labels: enhancement, backend

#171 [ORCT-153] - add field year
  app/lib/services/periods/PeriodService.js
Labels: bug, backend

#173 [ORCT-118] - bookkeeping service to sequelize
  app/lib/alimonitor-services/BookkeepingService.js
  app/lib/alimonitor-services/MonalisaService.js
  app/lib/alimonitor-services/ServicesDataCommons.js
  app/lib/database/repositories/Repository.js
  app/lib/utils/obj-utils.js
  database/stored-sql-functionalities/procedures/insert_detectors_for_runs.sql
  database/stored-sql-functionalities/procedures/insert_run.sql
  test/lib/utils/utils.test.js
Labels: refactor, backend

#174 amend detectos fetching
  app/lib/alimonitor-services/BookkeepingService.js
Labels: bug, backend

#178 [ORCT-163] - enhance sync logic
  app/application.js
  app/config/index.js
  app/config/rct-data/healthcheckQueries.js
  app/lib/alimonitor-services/SyncManager.js
  docker/dev.env
Labels: enhancement, backend

#180 amend bkp sync logs
  app/lib/alimonitor-services/BookkeepingService.js
  package.json
Labels: bug, backend

#181 rctmake rebuild option
  package.json
  rctmake
Labels: enhancement, backend

#185 [ORCT-118] - monalisa mc sync to sequelize
  app/lib/alimonitor-services/BookkeepingService.js
  app/lib/alimonitor-services/MonalisaService.js
  app/lib/alimonitor-services/MonalisaServiceDetails.js
  app/lib/alimonitor-services/MonalisaServiceMC.js
  app/lib/alimonitor-services/MonalisaServiceMCDetails.js
  app/lib/alimonitor-services/ServicesDataCommons.js
Labels: enhancement, refactor, backend

#186 Bind handle location change
  app/public/Model.js
  app/public/index.js
Labels: bug, frontend

#188 [ORCT-158] Rename site to page
  app/config/public.js
  app/lib/database/DatabaseService.js
  app/lib/database/utilities/PGQueryBuilder.js
  app/public/components/table/obsoletePager.js
  app/public/components/table/pageSelector.js
  app/public/components/table/pagerUtils.js
  app/public/components/table/pagination/PaginationModel.js
  app/public/model/UserPreferences.js
  app/public/model/data/FetchedData.js
  app/public/model/data/FetchedDataManager.js
  app/public/model/navigation/Navigation.js
  app/public/styles/rct/custom/components/pager.css
  app/public/views/runs/Runs.js
  app/public/views/runs/runsPerDataPass/overview/qcTypeSelection.js
  app/public/views/userView/data/pageSettings/pageSettings.js
  app/public/views/userView/data/pagesCellsSpecials.js
  app/public/views/userView/data/table/obsoleteItemsCounter.js
  test/database/utilities/PGQueryBuilder.test.js
  test/public/components/index.js
  test/public/components/pagerUtils.test.js
  test/public/utils/url/urlUtils.test.js
Labels: frontend, refactor

#187 [ORCT-167] find and count all
  app/lib/database/repositories/Repository.js
  app/lib/database/repositories/RunRepository.js
  app/lib/server/controllers/dataPass.controller.js
  app/lib/server/controllers/period.controller.js
  app/lib/server/controllers/qualityControl.controller.js
  app/lib/server/controllers/run.controller.js
  app/lib/server/controllers/simulationPass.controller.js
  app/lib/services/dataPasses/DataPassService.js
  app/lib/services/periods/PeriodService.js
  app/lib/services/qualityControl/QualityControlService.js
  app/lib/services/runs/RunService.js
  app/lib/services/simulationPasses/SimulationPassService.js
  app/lib/utils/adaptFindAndCountAllInService.js
  app/lib/utils/index.js
  test/lib/server/routes.test.js
Labels: enhancement, backend

#190 return correct value for run/det quality
  database/stored-sql-functionalities/functions/get_run_det_data.sql
Labels: bug, backend

#194 [ORCT-161] Make pager panel sticky
  app/public/styles/rct/custom/components/pager.css
Labels: enhancement, frontend

#191 Refactor/dev mode in legacy api
  app/application.js
  app/lib/database/DatabaseService.js
  app/lib/database/utilities/PGQueryBuilder.js
  app/lib/server/routers/index.js
  app/lib/utils/env-utils.js
  app/lib/utils/index.js
  package.json
  test/lib/server/routes.test.js
Labels: refactor, backend

#193 [ORCT-169] Display actual run detector qualities
  app/public/components/detectors/detectorIcon.js
Labels: frontend

#195 🐛 Fix/orct 169/detector qualities
  app/public/components/detectors/detectorIcon.js
Labels: bug
