Repository AliceO2Group/RunConditionTable, pull requests merged in 2023-07, with the labels that each got.

#122 Views and components refactor
  app/public/Model.js
  app/public/components/flags/flagsVisualization.js
  app/public/model/PrimaryModel.js
  app/public/views/flags/overview/flagsContent.js
  app/public/views/flags/overview/flagsPanel.js
  app/public/views/runs/Runs.js
  app/public/views/userView.js
  app/public/views/userView/data/dataPanel.js
  app/public/views/userView/data/pagesCellsSpecials.js
  app/public/views/userView/data/table/row.js
  app/public/views/userView/data/table/tablePanel.js
Labels: frontend, refactor

#126 🐛 Table name misspelling
  app/lib/database/procedures/flags.js
  app/lib/database/views/flags_view.js
  database/design.dbm
  database/exported/create-tables.sql
  docs/flags/mock.md
Labels: bug

#129 ORCT-45 filtering bugfix
  app/lib/database/QueryBuilder.js
Labels: bug

#130 ORCT-45 - between clause handle incorrect syntax, tests
  app/lib/database/QueryBuilder.js
  app/lib/database/index.js
  test/database/utilities/QueryBuilder.test.js
Labels: enhancement

#128 ORCT-45 Filtering
  app/config/public.js
  app/config/rct-data/filterTypes.js
  app/config/rct-data/flags.json
  app/config/rct-data/index.js
  app/config/rct-data/pageNames.js
  app/public/utils/filtering/filterUtils.js
  app/public/views/userView/data/table/filtering/activeFilters.js
  app/public/views/userView/data/table/filtering/filter.js
  app/public/views/userView/data/table/noDataView.js
  app/public/views/userView/data/table/tablePanel.js
Labels: frontend

#136 ORCT-95 Prepare data processing for list of energies in the period view
  app/config/public.js
  app/config/rct-data/index.js
  app/config/rct-data/mapping/beamType.js
  app/config/rct-data/mapping/energy.js
  app/config/rct-data/mapping/index.js
  app/lib/alimonitor-services/ServicesDataCommons.js
  app/public/utils/dataProcessing/dataProcessingUtils.js
  test/public/utils/dataProcessing.test.js
Labels: enhancement, frontend

#140 Improvement/ORCT-130/dockers dev test separation
  .env.test
  .github/workflows/run-tests.yml
  docker/application.dockerfile
  docker/database.dockerfile
  docker/dev.env
  docker/docker-compose-db-expose.yml
  docker/docker-compose-dev.yml
  docker/docker-compose-env.yml
  docker/docker-compose-test.yml
  docker/docker-compose-volumes.yml
  docker/docker-compose.yml
  docker/test.env
  package.json
  rctmake
  scripts/check-host-and-exec.sh
  test/database/DatabaseManger.test.js
  test/lib/config/publicConfigProvider.test.js
Labels: documentation, enhancement

#142 Improvement/backend cleanup
  app/application.js
  app/lib/database/DatabaseService.js
  app/lib/server/WebUiServer.js
  app/lib/server/index.js
  test/database/utilities/DatabaseService.test.js
  test/database/utilities/index.js
  test/lib/server/WebUiServer.test.js
  test/lib/server/index.js
Labels: refactor

#143 ORCT-130 rctmake bug
  rctmake
Labels: bug
