Repository AliceO2Group/RunConditionTable, pull requests merged in 2023-09, with the labels that each got.

#198 Refactor/orct 118/migration due to insert procedures changes
  app/lib/database/migrations/20230904071432-break-with-version-0-3-0.js
Labels: refactor, backend

#192 [ORCT-170] Runs per period new api
  app/public/Model.js
  app/public/views/periods/PeriodsModel.js
  app/public/views/runs/newRunsPerPeriod/RunsModel.js
  app/public/views/runs/newRunsPerPeriod/RunsPerPeriodModel.js
  app/public/views/runs/runsPerPeriod/overview/panel.js
Labels: frontend, refactor

#199 @aliceo2/run-condition-table@0.3.0
  package-lock.json
  package.json
Labels: release

#200 Update release procedure to remove deprecated use
  .github/workflows/release.yml
Labels: release

#201 Create CODEOWNERS
  .github/CODEOWNERS
Labels: CI

#202 [ORCT-177] Add dependabot auto-checker for dependencies
  .github/dependabot.yml
Labels: CI, dependencies, github_actions

#208 [ORCT-95] List of energies
  app/public/views/periods/ActiveColumns/periodsActiveColumns.js
  app/public/views/periods/PeriodsModel.js
  app/public/views/periods/overview/periodsContent.js
  app/public/views/periods/table/periodsTableHeader.js
  app/public/views/periods/table/periodsTableRow.js
  app/public/views/runs/newRunsPerPeriod/RunsPerPeriodModel.js
Labels: frontend

#210 [ORCT-118] bookkeeping services bugfix synchronization tests
  app/lib/alimonitor-services/AbstractServiceSynchronizer.js
  app/lib/alimonitor-services/BookkeepingService.js
  app/lib/alimonitor-services/helpers/Cacher.js
  app/lib/utils/http-utils.js
  docker/test.env
  hooks/pre-commit/newlines.sh
  test/lib/alimonitor-services/syncManager.test.js
  test/lib/alimonitor-services/testutil/cache-for-test.js
  test/lib/index.js
Labels: backend, bug, refactor

#215 [ORCT-118] monalisa service tests
  app/lib/alimonitor-services/BookkeepingService.js
  app/lib/alimonitor-services/helpers/Cacher.js
  docker/docker-compose-network.yml
  docker/test.env
  package.json
  rctmake
  test/lib/alimonitor-services/syncManager.test.js
  test/lib/alimonitor-services/testutil/bookkeeping-cache-test-data.js
  test/lib/alimonitor-services/testutil/common.js
  test/lib/alimonitor-services/testutil/monalisa-cache-test-data.js
Labels: backend, docker, documentation, javascript

#216 🐛 Handle middle logical operator
  app/lib/server/utilities/filterParser.js
  test/lib/server/filters.test.js
Labels: backend, bug

#217 [ORCT-180] Handle arrays in requests
  app/lib/server/utilities/filterParser.js
  docker/test.env
  test/lib/server/filters.test.js
Labels: backend, javascript

#218 [ORCT-182] add workaround for sequelize misbehaviour
  app/lib/server/utilities/filterParser.js
  test/lib/server/filters.test.js
Labels: backend, bug, javascript

#221 [ORCT-118] monalisa service mc test
  app/lib/alimonitor-services/BookkeepingService.js
  app/lib/alimonitor-services/MonalisaService.js
  app/lib/alimonitor-services/MonalisaServiceMC.js
  app/lib/alimonitor-services/helpers/ServicesDataCommons.js
  test/lib/alimonitor-services/syncManager.test.js
  test/lib/alimonitor-services/testutil/bookkeeping-cache-test-data.js
  test/lib/alimonitor-services/testutil/common.js
  test/lib/alimonitor-services/testutil/db-utils.js
  test/lib/alimonitor-services/testutil/monalisa-cache-test-data.js
  test/lib/alimonitor-services/testutil/monalisa-montecarlo-cache-test-data.js
Labels: backend, CI, javascript, refactor

#223 remove unnecessary db data amendment
  app/lib/database/migrations/20230904071432-break-with-version-0-3-0.js
Labels: DB

#224 [ORCT-188] adjust setup db script
  database/setup-db.sh
  docker/application.dockerfile
  docker/database.dockerfile
  docker/dev.env
Labels: DB, docker, refactor

#225 increase 'Periods overview - load the page test' timeout
  test/public/periods/overview.test.js
Labels: CI

#209 [ORCT-165] Data action buttons
  app/lib/server/utilities/filterParser.js
  app/lib/utils/ResProvider.js
  app/public/components/buttons/dataActionButtons.js
  app/public/components/filter/activeFilters.js
  app/public/components/filter/filteringPanel.js
  app/public/model/OverviewModel.js
  app/public/model/filtering/FilterModel.js
  app/public/model/navigation/ObsoleteNavigation.js
  app/public/utils/filtering/filterUtils.js
  app/public/views/flags/overview/flagsContent.js
  app/public/views/periods/PeriodsModel.js
  app/public/views/periods/overview/periodsContent.js
  app/public/views/periods/table/periodsTableRow.js
  app/public/views/runs/runsPerDataPass/overview/content.js
  app/public/views/runs/runsPerPeriod/overview/content.js
  app/public/views/userView/data/table/filtering/obsoleteActiveFilters.js
  app/public/views/userView/data/table/filtering/obsoleteFilter.js
  app/public/views/userView/data/table/tablePanel.js
  test/lib/server/filters.test.js
Labels: frontend, refactor

#226 [ORCT-186] review timestamps
  app/lib/database/adapters/QualityControlFlagAdapter.js
  app/lib/database/adapters/QualityControlFlagVerificationAdapter.js
  app/lib/database/migrations/20230816140200-create-periods.js
  app/lib/database/migrations/20230816140300-create-runs.js
  app/lib/database/migrations/20230816140500-create-data_passes.js
  app/lib/database/migrations/20230816140600-create-simulation_passes.js
  app/lib/database/migrations/20230816140700-create-runs_detectors.js
  app/lib/database/migrations/20230816140900-create-quality_control_flags.js
  app/lib/database/migrations/20230816141000-create-verifications.js
  app/lib/database/models/DataPass.js
  app/lib/database/models/Meta.js
  app/lib/database/models/Period.js
  app/lib/database/models/QualitControlFlag.js
  app/lib/database/models/QualityControlFlagVerification.js
  app/lib/database/models/Run.js
  app/lib/database/models/RunDetectors.js
  app/lib/database/models/SimulationPass.js
  app/lib/database/procedures/flags.js
  app/lib/database/views/flags_view.js
  app/lib/database/views/runs_views.js
  docs/flags/mock.md
Labels: backend, DB

#228 [ORCT-118] - handling incorrect data in montecarlo
  app/lib/alimonitor-services/MonalisaService.js
  app/lib/alimonitor-services/MonalisaServiceMC.js
  app/lib/alimonitor-services/helpers/ServicesDataCommons.js
  rctmake
Labels: backend

#229 [ORCT-118] extract find or create period
  app/lib/alimonitor-services/BookkeepingService.js
  app/lib/alimonitor-services/MonalisaService.js
  app/lib/alimonitor-services/MonalisaServiceDetails.js
  app/lib/alimonitor-services/MonalisaServiceMC.js
  app/lib/database/DatabaseManager.js
  app/lib/database/repositories/Repository.js
  app/lib/services/periods/findOrUpdateOrCreatePeriod.js
Labels: backend, refactor

#231 [ORCT-190] adjust db table
  app/config/rct-data/quality/flags.json
  app/lib/database/adapters/QualityControlFlagAdapter.js
  app/lib/database/migrations/20230816140800-create-flag_types_dictionary.js
  app/lib/database/migrations/20230816140900-create-quality_control_flags.js
  app/lib/database/models/FlagType.js
  app/lib/database/models/QualitControlFlag.js
  app/lib/server/controllers/qualityControl.controller.js
  app/lib/server/routers/qualityControl.router.js
  app/lib/services/qualityControl/QualityControlService.js
Labels: backend, DB

#232 Use correct default value for offset in legacy endpoints
  app/lib/database/utilities/PGQueryBuilder.js
Labels: backend, bug

#234 [ORCT-162] provide number of existing related data
  app/lib/database/adapters/PeriodAdapter.js
  app/lib/database/models/Period.js
  app/lib/services/periods/PeriodService.js
Labels: backend
